export type CivicStep={id:string;title:string;description:string;agency:string;mode:"Online"|"Physical"|"Hybrid";status:"complete"|"ready"|"blocked"|"optional";verification:"Official source"|"Human verified"|"Not verified";duration:string;documents:string[];sourceId:string;x:number;y:number};
export const sources=[
{id:"fssai",title:"Food Safety Compliance System (FoSCoS)",authority:"Food Safety and Standards Authority of India",url:"https://foscos.fssai.gov.in/",checked:"Official source checked · 28 Sep 2026",status:"Official portal"},
{id:"udyam",title:"Udyam Registration Portal",authority:"Ministry of Micro, Small & Medium Enterprises",url:"https://udyamregistration.gov.in/",checked:"Official source checked · 28 Sep 2026",status:"Official portal"},
{id:"gst",title:"GST Portal",authority:"Goods and Services Tax Network",url:"https://www.gst.gov.in/",checked:"Official source checked · 28 Sep 2026",status:"Official portal"},
{id:"mcgm",title:"BMC Health Licence guidance",authority:"Brihanmumbai Municipal Corporation",url:"https://portal.mcgm.gov.in/irj/servlet/prt/portal/prtroot/com.mcgm.acitizenservices_healthservices.HelpHealthLicense",checked:"Official source checked · 28 Sep 2026",status:"Official portal"},
];
export const steps:CivicStep[]=[
{id:"scope",title:"Confirm business profile",description:"Confirm premises, food activity, ownership and expected scale before choosing any registration path.",agency:"CivicFlow rules engine",mode:"Online",status:"complete",verification:"Human verified",duration:"2 min",documents:[],sourceId:"fssai",x:20,y:210},
{id:"premises",title:"Confirm the BMC Health Licence route",description:"Use BMC Health Licence guidance to confirm the municipal application route for the premises. BMC directs applicants to a Citizen Facilitation Centre and identifies an online citizen-portal route.",agency:"BMC",mode:"Hybrid",status:"ready",verification:"Official source",duration:"Check portal",documents:["Address proof","Premises proof"],sourceId:"mcgm",x:220,y:60},
{id:"fssai",title:"Determine FSSAI registration or licence",description:"Use FoSCoS eligibility to select the kind of business and applicable registration, State licence or Central licence. FSSAI states that petty food businesses with annual turnover up to ₹12 lakh use registration; other cases require a licence.",agency:"FSSAI",mode:"Online",status:"ready",verification:"Official source",duration:"Check portal",documents:["Identity proof","Premises proof","Food activity details"],sourceId:"fssai",x:220,y:210},
{id:"udyam",title:"Consider Udyam registration",description:"Optional MSME registration path. Review eligibility and submit only through the official portal.",agency:"Ministry of MSME",mode:"Online",status:"optional",verification:"Official source",duration:"Optional",documents:["Aadhaar","Business details"],sourceId:"udyam",x:220,y:360},
{id:"docs",title:"Prepare the portal-requested information",description:"Use the document lists shown by FoSCoS and BMC for the selected routes. This checklist records readiness only; each authority controls its final requirements.",agency:"FSSAI and BMC",mode:"Online",status:"blocked",verification:"Official source",duration:"Check portals",documents:["Identity proof","Address proof","Premises proof","Food activity details"],sourceId:"fssai",x:460,y:135},
{id:"gst",title:"Evaluate GST applicability separately",description:"GST registration is a separate tax decision and does not block this planning path. Use the official GST portal and current law to determine whether it applies.",agency:"GSTN",mode:"Online",status:"optional",verification:"Official source",duration:"Optional",documents:["PAN","Business details"],sourceId:"gst",x:460,y:305},
{id:"apply",title:"Submit the applicable BMC and FSSAI applications",description:"Submit only through the linked BMC and FoSCoS routes after confirming the selected category, application details, fees and declarations on each portal.",agency:"FSSAI and BMC",mode:"Hybrid",status:"blocked",verification:"Official source",duration:"Check portals",documents:["Portal-requested information"],sourceId:"fssai",x:700,y:210},
{id:"ready",title:"Ready to operate",description:"Keep approvals, receipts and renewal dates in your workflow. This is a planning milestone, not legal clearance.",agency:"CivicFlow",mode:"Online",status:"blocked",verification:"Not verified",duration:"Milestone",documents:["Approvals and receipts"],sourceId:"mcgm",x:920,y:210},
];
export const dependencies=[["scope","premises"],["scope","fssai"],["scope","udyam"],["scope","gst"],["premises","docs"],["fssai","docs"],["docs","apply"],["apply","ready"]] as const;
export const sharedDocuments=[{name:"Identity proof",usedBy:3,state:"Ready"},{name:"Address proof",usedBy:2,state:"Needs upload"},{name:"Premises proof",usedBy:3,state:"Needs upload"},{name:"Business activity details",usedBy:2,state:"Draft"}];
export const translations={en:{label:"English",headline:"Government procedures, made understandable.",prompt:"What government task are you trying to complete?"},hi:{label:"हिंदी",headline:"सरकारी प्रक्रियाएँ, अब आसानी से समझें।",prompt:"आप कौन-सा सरकारी काम पूरा करना चाहते हैं?"},mr:{label:"मराठी",headline:"सरकारी प्रक्रिया, आता समजण्यास सोपी.",prompt:"तुम्हाला कोणते सरकारी काम पूर्ण करायचे आहे?"}} as const;
