export type CivicStep={id:string;title:string;description:string;agency:string;mode:"Online"|"Physical"|"Hybrid";status:"complete"|"ready"|"blocked"|"optional";verification:"Official source"|"Human verified"|"Not verified";duration:string;documents:string[];sourceId:string;x:number;y:number};
export const sources=[
{id:"fssai",title:"Food Safety Compliance System (FoSCoS)",authority:"Food Safety and Standards Authority of India",url:"https://foscos.fssai.gov.in/",checked:"Demo snapshot · 27 Sep 2026",status:"Official portal"},
{id:"udyam",title:"Udyam Registration Portal",authority:"Ministry of Micro, Small & Medium Enterprises",url:"https://udyamregistration.gov.in/",checked:"Demo snapshot · 27 Sep 2026",status:"Official portal"},
{id:"gst",title:"GST Portal",authority:"Goods and Services Tax Network",url:"https://www.gst.gov.in/",checked:"Demo snapshot · 27 Sep 2026",status:"Official portal"},
{id:"mcgm",title:"MyBMC services",authority:"Brihanmumbai Municipal Corporation",url:"https://www.mcgm.gov.in/",checked:"Demo snapshot · 27 Sep 2026",status:"Official portal"},
];
export const steps:CivicStep[]=[
{id:"scope",title:"Confirm business profile",description:"Confirm premises, food activity, ownership and expected scale before choosing any registration path.",agency:"CivicFlow rules engine",mode:"Online",status:"complete",verification:"Human verified",duration:"2 min",documents:[],sourceId:"fssai",x:20,y:210},
{id:"premises",title:"Check premises permissions",description:"Review the applicable municipal premises and local-use requirements for the selected address.",agency:"BMC",mode:"Hybrid",status:"ready",verification:"Not verified",duration:"Check portal",documents:["Address proof","Premises proof"],sourceId:"mcgm",x:220,y:60},
{id:"fssai",title:"Determine FSSAI route",description:"Use the official FoSCoS eligibility flow to determine the registration or licence category that applies.",agency:"FSSAI",mode:"Online",status:"ready",verification:"Official source",duration:"Check portal",documents:["Identity proof","Premises proof","Food activity details"],sourceId:"fssai",x:220,y:210},
{id:"udyam",title:"Consider Udyam registration",description:"Optional MSME registration path. Review eligibility and submit only through the official portal.",agency:"Ministry of MSME",mode:"Online",status:"optional",verification:"Official source",duration:"Optional",documents:["Aadhaar","Business details"],sourceId:"udyam",x:220,y:360},
{id:"docs",title:"Prepare shared document pack",description:"Collect reusable identity, address and premises documents once for dependent applications.",agency:"Multiple authorities",mode:"Online",status:"blocked",verification:"Human verified",duration:"1–2 hours",documents:["Identity proof","Address proof","Premises proof"],sourceId:"fssai",x:460,y:135},
{id:"gst",title:"Evaluate GST applicability",description:"Use the official GST portal and current guidance to determine whether registration applies to your circumstances.",agency:"GSTN",mode:"Online",status:"blocked",verification:"Not verified",duration:"Check portal",documents:["PAN","Business details"],sourceId:"gst",x:460,y:305},
{id:"apply",title:"Submit verified applications",description:"Submit the applicable applications only after reviewing each official portal’s current requirements.",agency:"Relevant authorities",mode:"Hybrid",status:"blocked",verification:"Official source",duration:"Varies",documents:["Shared document pack"],sourceId:"fssai",x:700,y:210},
{id:"ready",title:"Ready to operate",description:"Keep approvals, receipts and renewal dates in your workflow. This is a planning milestone, not legal clearance.",agency:"CivicFlow",mode:"Online",status:"blocked",verification:"Not verified",duration:"Milestone",documents:["Approvals and receipts"],sourceId:"mcgm",x:920,y:210},
];
export const dependencies=[["scope","premises"],["scope","fssai"],["scope","udyam"],["premises","docs"],["fssai","docs"],["fssai","gst"],["docs","apply"],["gst","apply"],["apply","ready"]] as const;
export const sharedDocuments=[{name:"Identity proof",usedBy:3,state:"Ready"},{name:"Address proof",usedBy:2,state:"Needs upload"},{name:"Premises proof",usedBy:3,state:"Needs upload"},{name:"Business activity details",usedBy:2,state:"Draft"}];
export const translations={en:{label:"English",headline:"Government procedures, made understandable.",prompt:"What government task are you trying to complete?"},hi:{label:"हिंदी",headline:"सरकारी प्रक्रियाएँ, अब आसानी से समझें।",prompt:"आप कौन-सा सरकारी काम पूरा करना चाहते हैं?"},mr:{label:"मराठी",headline:"सरकारी प्रक्रिया, आता समजण्यास सोपी.",prompt:"तुम्हाला कोणते सरकारी काम पूर्ण करायचे आहे?"}} as const;
