"use client";

import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { useState } from "react";
import { catalogueInventory, evaluateCatalogue } from "@/lib/catalogue";
import { procedureSources as sources } from "@/lib/procedures";
import { useLocalDemo } from "@/lib/local-demo";

export function AdminPanel({ active }: { active: string }) {
  const demo = useLocalDemo();
  const [evaluated, setEvaluated] = useState<ReturnType<typeof evaluateCatalogue> | null>(null);
  const [selected, setSelected] = useState("home-food-business");
  const inventory = catalogueInventory();
  const claims = inventory.find((entry) => entry.procedure.id === selected)!;
  const steps = claims.items;
  const totalSteps = inventory.reduce((total, entry) => total + entry.items.length, 0);
  const totalEdges = inventory.reduce((total, entry) => total + entry.edges.length, 0);
  return <section className="card min-w-0 p-5 sm:p-6" aria-label={`${active} demo workspace`}><p className="eyebrow">Browser-local demonstration</p><h2 className="mt-2 text-2xl font-semibold">{active}</h2>
    {active === "Overview" && <div className="mt-6 space-y-4 text-sm leading-6"><p>{inventory.length} sample procedures, {sources.length} official portal links, {totalSteps} sample planning steps and {totalEdges} dependency edges are available in the local catalogue.</p><p>Food-business source review: <b>{demo.review}</b>. Food sample version: <b>{demo.review === "approved" ? "v1.4" : "v1.3"}</b>.</p><p className="text-muted">Live crawling, authoritative snapshots and backend validation are not connected in this local demo. No production health metric is implied.</p><p>{1 + Object.keys(demo.workflows).length} sample roadmaps are saved in this browser. Each supports scenario comparison, document readiness and printable reports.</p><Link href="/demo" className="button-secondary">Explore all samples</Link></div>}
    {active === "Sources" && <div className="mt-6 grid gap-4 sm:grid-cols-2">{sources.map((source) => <article className="rounded-xl border border-line p-4" key={source.id}><h3 className="font-semibold">{source.title}</h3><p className="mt-2 text-xs leading-5 text-muted">{source.authority}</p><p className="mt-3 text-xs text-muted">{source.checked}</p><p className="mt-2 text-xs leading-5 text-muted">Used by: {inventory.filter((entry) => entry.items.some((step) => step.sourceId === source.id)).map((entry) => entry.procedure.title).join("; ")}</p><p className="mt-2 text-xs text-muted">Reference link; no captured requirement snapshot.</p><a href={source.url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 text-xs font-semibold text-brand">Open official portal <ExternalLink size={14} /></a></article>)}</div>}
    {active === "Claims" && <div className="mt-6 space-y-3"><label className="block text-sm font-medium">Review procedure<select className="field mt-2" value={selected} onChange={(event) => setSelected(event.target.value)}>{inventory.map(({ procedure }) => <option key={procedure.id} value={procedure.id}>{procedure.title}</option>)}</select></label><p className="text-xs text-muted">Default sample path · {claims.procedure.jurisdiction}</p>{steps.map((step) => <article className="rounded-xl border border-line p-4" key={step.id}><h3 className="font-semibold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{step.description}</p><span className="badge mt-3">Not verified from an official source</span><p className="mt-2 text-xs text-muted">Seeded planning example · authority reference: {step.agency}</p><a href={sources.find((source) => source.id === step.sourceId)!.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 text-xs text-brand underline">Inspect reference source</a></article>)}</div>}
    {active === "Procedures" && <div className="mt-6 grid gap-4">{inventory.map(({ procedure, items, edges }) => <article key={procedure.id} className="rounded-xl border border-line p-5"><span className="badge">Sample procedure {procedure.id === "home-food-business" ? demo.review === "approved" ? "v1.4" : "v1.3" : "v1.0"}</span><h3 className="mt-3 text-xl font-semibold">{procedure.title}</h3><p className="mt-2 text-sm text-muted">{procedure.jurisdiction}</p><p className="mt-3 text-sm leading-6 text-muted">{items.length} steps · {edges.length} dependencies · {items.filter((step) => step.status === "optional").length} optional. {procedure.description}</p><div className="mt-4 flex flex-wrap gap-3"><Link href={`/app/goals/${procedure.id}/roadmap`} className="button-primary text-xs">Open procedure graph</Link><Link href={`/app/goals/${procedure.id}/what-if`} className="button-secondary text-xs">Compare scenarios</Link><Link href={`/app/goals/${procedure.id}/documents`} className="button-secondary text-xs">Readiness</Link><Link href={`/app/goals/${procedure.id}/print`} className="button-secondary text-xs">Print / PDF</Link></div></article>)}</div>}
    {active === "Evaluations" && <div className="mt-6 space-y-4"><p className="text-sm leading-6 text-muted">Run the local compiler for every supported intake combination. Check graph references, acyclicity and whether all required steps can be completed. These checks do not assess legal correctness or external AI.</p><button className="button-primary" onClick={() => setEvaluated(evaluateCatalogue())}>Run graph checks</button>{evaluated && <div aria-live="polite" className="space-y-3"><p className="text-sm font-semibold">{evaluated.totalVariants} scenario variants checked · {evaluated.valid && evaluated.sourceLinksValid ? "Pass" : "Fail"}</p><p className="text-xs text-muted">Official reference links use HTTPS: {evaluated.sourceLinksValid ? "Pass" : "Fail"}</p><ul className="space-y-3">{evaluated.results.map((result) => <li key={result.id} className="rounded-xl border border-line p-4 text-sm"><b>{result.title}</b><p className="mt-2">{result.variants} variants · {result.valid ? "Pass" : "Fail"}</p>{result.errors.map((error) => <p key={error} className="mt-2 text-red-700">{error}</p>)}</li>)}</ul></div>}</div>}
    {active === "Audit log" && <div className="mt-6">{demo.audit.length === 0 ? <p className="text-sm text-muted">No local review decisions yet. Approve or reject the synthetic food-business change to create a demo audit entry.</p> : <ol className="space-y-3">{demo.audit.toReversed().map((entry, index) => <li key={`${entry.at}-${index}`} className="rounded-xl border border-line p-4"><p className="text-sm font-semibold">{entry.action}</p><time dateTime={entry.at} className="mt-2 block text-xs text-muted">{new Date(entry.at).toLocaleString()}</time></li>)}</ol>}<p className="mt-5 text-xs text-muted">Demo events are stored only in this browser. This is not a server audit trail.</p></div>}
  </section>;
}
