"use client";
import Link from "next/link";import {useSearchParams} from "next/navigation";import {ArrowLeft,ArrowRight,Check,MapPin,ShieldCheck,Sparkles} from "lucide-react";import {useEffect,useState} from "react";import {SiteHeader} from "@/components/site-header";
const pipeline=["Understanding your goal","Resolving jurisdiction","Finding official sources","Structuring requirements","Checking dependencies","Building your roadmap"];
export function DemoFlow(){const params=useSearchParams();const goal=params.get("goal")||"Start a home food business in Mumbai";const[stage,setStage]=useState<"questions"|"building"|"ready">("questions");const[progress,setProgress]=useState(0);
useEffect(()=>{if(stage!=="building")return;const id=setInterval(()=>setProgress(p=>{if(p>=pipeline.length){clearInterval(id);setStage("ready");return p}return p+1}),520);return()=>clearInterval(id)},[stage]);
return <><SiteHeader compact/><main className="shell py-10"><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted"><ArrowLeft size={16}/>Back</Link><div className="mx-auto mt-10 max-w-3xl"><div className="flex items-center justify-between"><div><p className="eyebrow">Deterministic judge demo</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Let’s personalize your path.</h1></div><span className="badge hidden sm:flex"><ShieldCheck size={13}/>Offline-safe</span></div>
<div className="card mt-8 p-6 md:p-8"><div className="rounded-2xl bg-surface-2 p-4"><p className="text-xs font-semibold text-muted">YOUR GOAL</p><p className="mt-2 font-semibold">“{goal}”</p><div className="mt-3 flex items-center gap-2 text-sm text-brand"><MapPin size={15}/>India / Maharashtra / Mumbai / BMC</div></div>
{stage==="questions"&&<div className="mt-7 space-y-6"><Question label="Where will you operate?" hint="This selects the applicable municipal authority."><select className="mt-2 w-full rounded-xl border border-line bg-surface px-4 py-3"><option>Home premises in Mumbai</option><option>Commercial premises in Mumbai</option></select></Question><Question label="What will you primarily do?" hint="The activity changes the official eligibility path."><select className="mt-2 w-full rounded-xl border border-line bg-surface px-4 py-3"><option>Prepare and deliver food</option><option>Package food products</option><option>Resell packaged goods</option></select></Question><Question label="Do you already have a food business registration or licence?" hint="We will hide steps you have already completed."><div className="mt-2 grid grid-cols-2 gap-3"><label className="rounded-xl border border-brand bg-brand/5 px-4 py-3"><input defaultChecked type="radio" name="existing" className="mr-2"/>No</label><label className="rounded-xl border border-line px-4 py-3"><input type="radio" name="existing" className="mr-2"/>Yes</label></div></Question><button className="button-primary w-full" onClick={()=>setStage("building")}>Compile my roadmap <ArrowRight size={17}/></button></div>}
{stage==="building"&&<div className="mt-8"><div className="mb-7 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-accent text-accent-ink"><Sparkles size={18}/></span><div><p className="font-semibold">Compiling your procedure</p><p className="text-sm text-muted">Using cached official-source snapshots for a reliable demo.</p></div></div><div className="space-y-3">{pipeline.map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl border border-line px-4 py-3"><span className={`grid size-6 place-items-center rounded-full text-xs ${i<progress?"bg-brand text-white":i===progress?"bg-accent text-accent-ink":"bg-surface-2 text-muted"}`}>{i<progress?<Check size={14}/>:i+1}</span><span className={i>progress?"text-muted":""}>{x}</span>{i===progress&&<span className="ml-auto size-2 animate-pulse rounded-full bg-brand"/>}</div>)}</div></div>}
{stage==="ready"&&<div className="mt-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-brand text-white"><Check size={28}/></span><h2 className="mt-5 text-2xl font-semibold">Your roadmap is ready</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted">8 steps · 4 official portals · 2 parallel paths · every factual item carries a verification label.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link className="button-primary" href="/app/goals/home-food-business/roadmap">Open interactive roadmap <ArrowRight size={17}/></Link><Link className="button-secondary" href="/admin">See validation console</Link></div></div>}
</div><p className="mt-4 text-center text-xs leading-5 text-muted">Demo data is clearly labelled and must not be treated as legal advice. Always confirm current requirements on the linked official portal.</p></div></main></>}
function Question({label,hint,children}:{label:string;hint:string;children:React.ReactNode}){return <fieldset><legend className="font-semibold">{label}</legend><p className="mt-1 text-xs text-muted">{hint}</p>{children}</fieldset>}
